server:
  servlet:
    context-path: /frent
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/osago?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  thymeleaf:
      cache: false

files:
  path:
    icons: "/Users/serge/Documents/upload/icons"
    images: "/Users/serge/Documents/upload/images"
